version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: America/Sao_Paulo
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  reviewers:
  - victorheringer
  - murillo94
  - julianosbento
  - an-mag
  - pleaobraga
  - carlosberti
  - lopesalysson
  - pedro-cerdera
  assignees:
  - victorheringer
  - murillo94
  - julianosbento
  - an-mag
  - pleaobraga
  - carlosberti
  - lopesalysson
  - pedro-cerdera
  ignore:
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: cssnano
    versions:
    - 4.1.11
  - dependency-name: stylelint
    versions:
    - 13.12.0
  - dependency-name: svgo
    versions:
    - 2.2.2
  - dependency-name: postcss-url
    versions:
    - 9.0.0
  - dependency-name: stylelint-config-standard
    versions:
    - 20.0.0
  - dependency-name: postcss-cli
    versions:
    - 7.1.2
